# Generated by Django 2.0.2 on 2018-03-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(default='rasul.hasen@gmail.com', max_length=140),
        ),
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(default='NoName', max_length=45),
        ),
    ]
